# Sim 3 v3 truth-init diagnostic
#
# Discriminate mixing-vs-landscape on the v3 redesigned dataset:
#   - Aware chain initialised at TRUTH tree + truth parameters
#     (phi=4, pi0=0.75, theta=1, rate_neo=1, tl=truth)
#   - If chain stays near truth: random-init chain fails because of
#     MIXING; we know the posterior peaks at truth.
#   - If chain drifts away from truth: posterior peaks elsewhere
#     (landscape problem; rate_neo or other identifiability issue
#     creates a competing mode).
#
# Reads the v3 dataset from result.rds (must have been generated by
# bayesian-pilot.R).
#
# Run from worktree root:
#   Rscript -e "setwd('C:/Users/pjjg18/GitHub/mkp/.claude/worktrees/ecology-aware'); source('dev/pilots/2026-05-14-sim3-v3-redesign/truth-init.R')"

suppressPackageStartupMessages({
  devtools::load_all(".", quiet = TRUE)
  library("TreeTools")
})
source("inst/simulations/ecology/sim3-helpers.R")

PILOT_DIR <- "dev/pilots/2026-05-14-sim3-v3-redesign"
saved <- readRDS(file.path(PILOT_DIR, "result.rds"))

tree <- saved$tree
eco  <- saved$eco
datSim <- saved$data
nEco <- saved$config$nEco

pdSim <- MatrixToPhyDat(datSim)
mkdAware <- MkPrimeData(pdSim, neomorphic = seq_len(nEco), ecology = eco)

modelAware <- MkPrimeModel(ecologyAware = TRUE,
                           magnitudeMode = "global",
                           kPrimePrior = "geometric",
                           coding = "variable", expSteps = 10)

# Truth-init: override .InitState in MkPrime namespace so chain starts
# at truth params. Then restore at the end.
origInit <- MkPrime:::.InitState
truthInit <- function(mkd, model, mcmc, tree = NULL, ...) {
  st <- origInit(mkd = mkd, model = model, mcmc = mcmc, tree = saved$tree, ...)
  # Override aware-relevant params at truth
  st$phi <- saved$config$phi
  st$pi0 <- 0.75
  st$theta <- 1.0
  st$rate_neo <- 1.0
  st$rate_loss <- 1.0
  st$tree_length <- saved$truthTL
  # z matrix at truth
  zTruth <- saved$z[, -1L, drop = FALSE]  # drop ref-eco column
  storage.mode(zTruth) <- "integer"
  st$zMatrix <- zTruth
  st
}
assignInNamespace(".InitState", truthInit, ns = "MkPrime")
cat("[patch] .InitState replaced with truth-init\n")

nIter <- 50000L
thin <- 40L
mcmc <- MkPrimeMCMC(nIter = nIter, nChains = 1L, nRuns = 1L,
                    thin = thin, treeThin = thin,
                    minWarmup = 1000L, maxWarmup = 2000L,
                    logFile = NULL, checkpointFile = NULL)
logFile <- file.path(PILOT_DIR, "truth-init-chain.log")
ckpFile <- file.path(PILOT_DIR, "truth-init-chain.ckp")
for (f in c(logFile, ckpFile)) if (file.exists(f)) file.remove(f)
mcmc$logFile <- logFile
mcmc$checkpointFile <- ckpFile

cat("\n== Running truth-init aware chain (nIter=", nIter, ") ==\n")
t0 <- Sys.time()
res <- tryCatch(RunMkPrime(mkdAware, tree = saved$tree,
                            model = modelAware, mcmc = mcmc),
                error = function(e) {
                  cat("ERROR:", conditionMessage(e), "\n"); NULL
                })
cat("Elapsed:", format(Sys.time() - t0), "\n")
assignInNamespace(".InitState", origInit, ns = "MkPrime")
cat("[patch] .InitState restored\n")

if (!is.null(res)) {
  res <- RelabelEcology(res)
  saveRDS(list(res = res, truthTL = saved$truthTL,
               phi_true = saved$config$phi),
          file.path(PILOT_DIR, "truth-init-result.rds"))
  cat("Saved truth-init-result.rds\n")
}
