# Shared reference-run config for the §7a bit-identity regression test.
#
# IMPORTANT: this helper defines the ONLY source of truth for what
# .RunPartitionBitcompatReference() does. The reference RDS in
# tests/testthat/_reference/partition-bitcompat-null-ref.rds was generated by
# tests/testthat/_reference/generate-partition-bitcompat-null.R using this
# helper. The §7a regression test must call this helper and compare against
# the stored RDS.
#
# Any change to this helper invalidates the stored reference. Do not modify
# without regenerating the RDS AND setting out, in the pull request that does
# it, the behavioural change to the legacy partition = NULL code path (which
# the §7a contract forbids except in the rate_neo -> eta_neo case noted in
# §7c). The PR is the record; NEWS.md is not written to (see AGENTS.md).
#
# HERMETICITY (2026-09-18). The fixture pins its own starting tree, read from
# _reference/partition-bitcompat-null-start.nwk. It must never call
# RunMkPrime(tree = NULL): that delegates the starting topology to
# TreeSearch::AdditionTree() when TreeSearch is installed, so the whole chain
# then depends on the version of a *Suggests* package that nothing pins. That
# is what invalidated the previous reference — it became unreproducible from
# the very commit that generated it (2b3c054) as soon as the installed
# TreeSearch moved on, and CI, which resolves TreeSearch from CRAN, could
# never reproduce it at all. A comparator whose inputs are not pinned is not
# a comparator.
#
# The model is pinned the same way, argument by argument, so that a change to
# a MkPrimeModel() default cannot move the reference; see below.
#
# The MCMC itself is reproducible given a pinned tree: on every CI platform
# the 5 x 211 sample matrix comes back identical to the reference save for
# last-bit noise, and the accept/reject trajectory is the same everywhere.
# What is NOT reproducible across platforms is the final bit of every sum;
# see the note on the reference platform below.

# Dataset: Lobo.phy via TreeTools::data(Lobo.phy). 48 tips, 110 chars after
# invariant drop, all transformational (verified 2026-05-20; the same five
# columns 17, 48, 106, 109, 115 are dropped in CI and locally). No neomorphic
# chars => rate_neo / eta_neo code path is never exercised, so the §7a
# bit-identity guarantee is robust under both readings of the rate_neo ->
# eta_neo reparameterisation (§7c).


# The platform the stored reference was generated on, and why the comparison
# is by tolerance rather than by bits.
#
# The reference RDS was generated on x86_64 Windows (mingw-w64). Run against
# it on 2026-09-19 the six CI jobs split cleanly, each group internally
# bit-identical:
#
#   x86_64 Linux (release and devel) and x86_64 macOS  ->  one element of
#     result$samples differs from the reference by exactly one ULP:
#     log_posterior of sample 2, -878.6662799424009 against ...08. The other
#     1054 elements are bit-identical, so the trajectory did not diverge: the
#     difference is one rounding in one transcendental call, not a different
#     chain. That is the C library, not the package -- glibc, Apple libm and
#     mingw-w64's msvcrt do not agree on the last bit of log() / exp().
#
#   aarch64 Linux and aarch64 macOS  ->  a wider last-bit spread, from FMA
#     contraction on top of the libm difference: arm64 toolchains contract
#     `a * b + c` into a fused multiply-add that rounds once where baseline
#     x86-64 rounds twice. Most legible in the pinned starting tree's own
#     total length, 9.4 summed over 94 edges of 0.1, coming back as
#     9.399999999999980. Both jobs pass the 1e-9 tolerance.
#
# No pinning can remove either effect, so the fixture does not ask for
# bit-identity: it asserts a 1e-9 tolerance on every platform, and keeps the
# schema assertions exact. An earlier attempt to keep a bit-exact branch on a
# matching CPU architecture (2026-09-18) failed because the architecture is
# the wrong axis -- x86_64 Linux and x86_64 Windows disagree while sharing an
# arch, and the toolchain axis would make one CI job hostage to whichever
# libm its runner image ships.
#
# The tolerance retains the power the comparator is for. The chain is
# chaotic: any genuine change to the legacy path flips an accept/reject
# within a few iterations and diverges by whole nats -- a relative difference
# near 1e-3, thirteen orders of magnitude above the ~2e-16 relative spread
# seen between platforms, with the 1e-9 tolerance six orders below it. What a
# tolerant comparison cannot catch is a drift smaller than that spread, which
# no comparator run on more than one machine could catch either.
#
# Bit-identity where it IS a real property -- two runs of the same build in
# the same process under the same seed -- is asserted by
# test-determinism-gibbs-subtree-swap.R.
#
# Update this note only when regenerating the reference on a different
# machine.

# Path of the pinned starting tree, relative to tests/testthat/.
.PartitionBitcompatStartTreePath <- function() {
  testthat::test_path("_reference", "partition-bitcompat-null-start.nwk")
}

# The model is pinned argument by argument rather than taken from
# MkPrimeModel()'s defaults, which are not an input the fixture controls: the
# reference was rewritten in ada6bb7 and again in 2b3c054 because a prior
# default moved under it, each rewrite indistinguishable from evading the
# guard. A default flip now changes the package and leaves the comparator
# standing. Changing a value here is a deliberate act, recorded in the PR.
.PartitionBitcompatModelArgs <- function() {
  list(
    coding                 = "variable",
    nCat                   = 6L,
    relabel                = TRUE,
    treeLengthShape        = 2,
    treeLengthRate         = NULL,
    expSteps               = NULL,
    rateLossMeanlog        = 0,
    rateLossSdlog          = 2,
    rateLogSdShape         = 1,
    rateLogSdRate          = 1,
    kPrimePrior            = "empirical_geometric",
    empiricalNObs          = NULL,
    kprimeHyperA           = 1,
    kprimeHyperB           = 1,
    kprimeAlpha            = 1,
    kprimeBeta             = 1,
    kprimeLogseriesC       = 0.7,
    rateNeoMeanlog         = 0,
    rateNeoSdlog           = 2,
    qHeterogeneity         = FALSE,
    nBetaCat               = 4L,
    betaScaleShape         = 1,
    betaScaleRate          = 1,
    classRateConcentration = 1,
    priorOnClassRateLogSd  = "hyperprior_pooled",
    likelihoodMode         = "sampled_k",
    # Resolved, not left to MkPrimeModel() to derive from kPrimePrior.
    priorVariant           = "unconditional",
    kprimeTruncK           = 200L
  )
}

# Pinning covers only the arguments that existed when the reference was
# generated; a new one would slip past it. test-partition-bitcompat-null.R
# asserts this signature, so adding a knob to MkPrimeModel() forces an
# explicit decision about whether it belongs in the legacy path.
.PartitionBitcompatModelFormals <- function() {
  names(.PartitionBitcompatModelArgs())
}

.RunPartitionBitcompatReference <- function() {
  # Lobo.phy is exported as an object from TreeTools (not a data() dataset).
  pd <- TreeTools::Lobo.phy
  mkd <- MkPrimeData(pd)

  # kprimeLogseriesC is pinned but not passed: MkPrimeModel() warns that it is
  # ignored under empirical_geometric, and an ignored value cannot move the
  # chain.
  modelArgs <- .PartitionBitcompatModelArgs()
  modelArgs[["kprimeLogseriesC"]] <- NULL
  model <- do.call(MkPrimeModel, modelArgs)

  # nIter / maxWarmup are SHORTER than the plan's nominal "1000 iter" target.
  # Bisected 2026-05-20: with gibbsSubtreeSwap=FALSE and joint2d=FALSE,
  # cross-process bit-identity holds at (nIter=100, maxWarmup=50) but breaks
  # somewhere before (nIter=1000, maxWarmup=200) — a third nondeterminism
  # source emerges in longer chains. Shortening preserves the §7a contract's
  # intent (detect drift in the legacy code path after partition-API edits)
  # without depending on un-tracked-down cross-process nondeterminism in the
  # existing move set. The remote-agent rule "≤ 1000 generations for smoke
  # tests" is comfortably satisfied.
  mcmc <- MkPrimeMCMC(
    nIter        = 100L,
    maxWarmup    = 50L,
    minWarmup    = 50L,
    thin         = 10L,
    nRuns        = 1L,
    nChains      = 1L,
    nCore        = 1L,
    autoTune     = FALSE,   # adaptive tuning off for tightest determinism
    minEss       = NULL,
    maxRhat      = NULL,
    minTreeEss   = NULL,
    maxTime      = NULL,
    checkEvery   = 1000L,
    logFile      = NULL,
    treeFile     = NULL,
    checkpointFile = NULL,
    progressFn   = NULL,
    # gibbsSubtreeSwap must be off — it breaks bit-identity even within a
    # single process across two seeded runs (real bug in the existing move
    # on main, separately filed for fix).
    #
    # joint2d is kept off as a belt-and-braces precaution. A re-investigation
    # 2026-05-20 (joint2d agent) confirmed joint2d itself is deterministic
    # both within and across processes, so this is not strictly required —
    # but the §7a reference was generated with it off, so keep this until
    # the reference is regenerated.
    #
    # A SEPARATE, currently-uncharacterised cross-process divergence
    # emerges at longer chains (≥1000 iter / ≥200 warmup) even with both
    # gibbsSubtreeSwap and joint2d off. The §7a reference accordingly uses
    # the short (100 iter / 50 warmup) regime where bit-identity holds.
    #
    # gibbsSpr is pinned off because this reference guards the legacy path as
    # a whole, not any one move. It is also the one move on main known to be
    # incorrect (issue #19: no MH step, so not pi-invariant), and its fix is
    # in flight (PR #30). Leaving it on would make the reference hostage to
    # that fix, forcing a regeneration indistinguishable from evading the
    # guard. gibbs_spr correctness is covered by test-gibbs-spr.R,
    # test-gibbs-spr-candidates.R and the detailed-balance gate at
    # dev/red-team/heavy-tests/gibbs-spr-db.R.
    gibbsSpr         = FALSE,
    #
    # pSpr is pinned off for the same reason as gibbsSpr: it was the other move
    # on main known to be incorrect (issue #142 -- candidate parsimony weights
    # were a function of the edge-array row layout, so the move was not
    # pi-invariant), and leaving it on made the reference hostage to that fix.
    # pspr correctness is covered by test-pspr.R and
    # test-topology-detailed-balance.R.
    pSpr             = FALSE,
    #
    # cacheBonus is pinned off (1 = no boost) for the same reason: the boost
    # rule made move selection depend on the chain's state (issue #70), and its
    # fix changes which moves are drawn, so leaving it on made the reference
    # hostage to that fix. Its correctness is covered by
    # test-cache-aware-scheduling.R.
    cacheBonus       = 1,
    gibbsSubtreeSwap = FALSE,
    joint2d          = FALSE
  )

  # The pinned starting tree: a greedy parsimony addition tree over Lobo.phy
  # with every edge set to 0.1 (total length 9.4), captured once to Newick so
  # that no installed package decides it. ape::read.tree is deterministic for
  # a fixed string, which is the only property the fixture needs — the edge
  # ordering need not match whatever produced the string.
  tree <- ape::read.tree(.PartitionBitcompatStartTreePath())

  set.seed(20260520L)
  RunMkPrime(data = mkd, tree = tree, model = model, mcmc = mcmc,
             fixTopology = FALSE, overwrite = TRUE)
}

# Path of the locked reference RDS, relative to tests/testthat/.
.PartitionBitcompatReferencePath <- function() {
  testthat::test_path("_reference", "partition-bitcompat-null-ref.rds")
}
