# Shared reference-run config for the §7a bit-identity regression test.
#
# IMPORTANT: this helper defines the ONLY source of truth for what
# .RunPartitionBitcompatReference() does. The reference RDS in
# tests/testthat/_reference/partition-bitcompat-null-ref.rds was generated by
# tests/testthat/_reference/generate-partition-bitcompat-null.R using this
# helper. The §7a regression test must call this helper and compare against
# the stored RDS via expect_identical().
#
# Any change to this helper invalidates the stored reference. Do not modify
# without regenerating the RDS AND updating NEWS.md to record the behavioural
# change to the legacy partition = NULL code path (which the §7a contract
# forbids except in the rate_neo -> eta_neo case noted in §7c).
#
# HERMETICITY (2026-09-18). The fixture pins its own starting tree, read from
# _reference/partition-bitcompat-null-start.nwk. It must never call
# RunMkPrime(tree = NULL): that delegates the starting topology to
# TreeSearch::AdditionTree() when TreeSearch is installed, so the whole chain
# then depends on the version of a *Suggests* package that nothing pins. That
# is what invalidated the previous reference — it became unreproducible from
# the very commit that generated it (2b3c054) as soon as the installed
# TreeSearch moved on, and CI, which resolves TreeSearch from CRAN, could
# never reproduce it at all. A comparator whose inputs are not pinned is not
# a comparator.
#
# The MCMC itself is bit-identical given a pinned tree: the same values arise
# on x86_64 Linux, aarch64 Linux, macOS and Windows, under both R release and
# R devel.

# Dataset: Lobo.phy via TreeTools::data(Lobo.phy). 48 tips, 110 chars after
# invariant drop, all transformational (verified 2026-05-20; the same five
# columns 17, 48, 106, 109, 115 are dropped in CI and locally). No neomorphic
# chars => rate_neo / eta_neo code path is never exercised, so the §7a
# bit-identity guarantee is robust under both readings of the rate_neo ->
# eta_neo reparameterisation (§7c).

# Path of the pinned starting tree, relative to tests/testthat/.
.PartitionBitcompatStartTreePath <- function() {
  testthat::test_path("_reference", "partition-bitcompat-null-start.nwk")
}

.RunPartitionBitcompatReference <- function() {
  # Lobo.phy is exported as an object from TreeTools (not a data() dataset).
  pd <- TreeTools::Lobo.phy
  mkd <- MkPrimeData(pd)

  model <- MkPrimeModel()  # all defaults — bit-identity guard against drift

  # nIter / maxWarmup are SHORTER than the plan's nominal "1000 iter" target.
  # Bisected 2026-05-20: with gibbsSubtreeSwap=FALSE and joint2d=FALSE,
  # cross-process bit-identity holds at (nIter=100, maxWarmup=50) but breaks
  # somewhere before (nIter=1000, maxWarmup=200) — a third nondeterminism
  # source emerges in longer chains. Shortening preserves the §7a contract's
  # intent (detect drift in the legacy code path after partition-API edits)
  # without depending on un-tracked-down cross-process nondeterminism in the
  # existing move set. The remote-agent rule "≤ 1000 generations for smoke
  # tests" is comfortably satisfied.
  mcmc <- MkPrimeMCMC(
    nIter        = 100L,
    maxWarmup    = 50L,
    minWarmup    = 50L,
    thin         = 10L,
    nRuns        = 1L,
    nChains      = 1L,
    nCore        = 1L,
    autoTune     = FALSE,   # adaptive tuning off for tightest determinism
    minEss       = NULL,
    maxRhat      = NULL,
    minTreeEss   = NULL,
    maxTime      = NULL,
    checkEvery   = 1000L,
    logFile      = NULL,
    treeFile     = NULL,
    checkpointFile = NULL,
    progressFn   = NULL,
    # gibbsSubtreeSwap must be off — it breaks bit-identity even within a
    # single process across two seeded runs (real bug in the existing move
    # on main, separately filed for fix).
    #
    # joint2d is kept off as a belt-and-braces precaution. A re-investigation
    # 2026-05-20 (joint2d agent) confirmed joint2d itself is deterministic
    # both within and across processes, so this is not strictly required —
    # but the §7a reference was generated with it off, so keep this until
    # the reference is regenerated.
    #
    # A SEPARATE, currently-uncharacterised cross-process divergence
    # emerges at longer chains (≥1000 iter / ≥200 warmup) even with both
    # gibbsSubtreeSwap and joint2d off. The §7a reference accordingly uses
    # the short (100 iter / 50 warmup) regime where bit-identity holds.
    gibbsSubtreeSwap = FALSE,
    joint2d          = FALSE
  )

  # The pinned starting tree: a greedy parsimony addition tree over Lobo.phy
  # with every edge set to 0.1 (total length 9.4), captured once to Newick so
  # that no installed package decides it. ape::read.tree is deterministic for
  # a fixed string, which is the only property the fixture needs — the edge
  # ordering need not match whatever produced the string.
  tree <- ape::read.tree(.PartitionBitcompatStartTreePath())

  set.seed(20260520L)
  RunMkPrime(data = mkd, tree = tree, model = model, mcmc = mcmc,
             fixTopology = FALSE, overwrite = TRUE)
}

# Path of the locked reference RDS, relative to tests/testthat/.
.PartitionBitcompatReferencePath <- function() {
  testthat::test_path("_reference", "partition-bitcompat-null-ref.rds")
}
