// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pruning_jc_acrv
double pruning_jc_acrv(Rcpp::IntegerVector parent, Rcpp::IntegerVector child, Rcpp::NumericVector edge_length, Rcpp::IntegerMatrix tip_states, int kStates, Rcpp::NumericVector root_freqs, Rcpp::NumericVector rate_multipliers);
RcppExport SEXP _MkPrime_pruning_jc_acrv(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP tip_statesSEXP, SEXP kStatesSEXP, SEXP root_freqsSEXP, SEXP rate_multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< int >::type kStates(kStatesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type root_freqs(root_freqsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rate_multipliers(rate_multipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(pruning_jc_acrv(parent, child, edge_length, tip_states, kStates, root_freqs, rate_multipliers));
    return rcpp_result_gen;
END_RCPP
}
// pruning_jc_acrv_collapsed
double pruning_jc_acrv_collapsed(Rcpp::IntegerVector parent, Rcpp::IntegerVector child, Rcpp::NumericVector edge_length, Rcpp::IntegerMatrix tip_states, int kFull, int kObs, Rcpp::NumericVector rate_multipliers);
RcppExport SEXP _MkPrime_pruning_jc_acrv_collapsed(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP tip_statesSEXP, SEXP kFullSEXP, SEXP kObsSEXP, SEXP rate_multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< int >::type kFull(kFullSEXP);
    Rcpp::traits::input_parameter< int >::type kObs(kObsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rate_multipliers(rate_multipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(pruning_jc_acrv_collapsed(parent, child, edge_length, tip_states, kFull, kObs, rate_multipliers));
    return rcpp_result_gen;
END_RCPP
}
// pruning_mkn_acrv
double pruning_mkn_acrv(Rcpp::IntegerVector parent, Rcpp::IntegerVector child, Rcpp::NumericVector edge_length, Rcpp::IntegerMatrix tip_states, double rate_loss, Rcpp::NumericVector root_freqs, Rcpp::NumericVector rate_multipliers);
RcppExport SEXP _MkPrime_pruning_mkn_acrv(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP tip_statesSEXP, SEXP rate_lossSEXP, SEXP root_freqsSEXP, SEXP rate_multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< double >::type rate_loss(rate_lossSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type root_freqs(root_freqsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rate_multipliers(rate_multipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(pruning_mkn_acrv(parent, child, edge_length, tip_states, rate_loss, root_freqs, rate_multipliers));
    return rcpp_result_gen;
END_RCPP
}
// constant_site_prob_jc
double constant_site_prob_jc(Rcpp::IntegerVector parent, Rcpp::IntegerVector child, Rcpp::NumericVector edge_length, int nTip, int kStates, Rcpp::NumericVector root_freqs, Rcpp::NumericVector rate_multipliers);
RcppExport SEXP _MkPrime_constant_site_prob_jc(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP nTipSEXP, SEXP kStatesSEXP, SEXP root_freqsSEXP, SEXP rate_multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< int >::type kStates(kStatesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type root_freqs(root_freqsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rate_multipliers(rate_multipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(constant_site_prob_jc(parent, child, edge_length, nTip, kStates, root_freqs, rate_multipliers));
    return rcpp_result_gen;
END_RCPP
}
// singleton_site_prob_jc
double singleton_site_prob_jc(Rcpp::IntegerVector parent, Rcpp::IntegerVector child, Rcpp::NumericVector edge_length, int nTip, int kStates, Rcpp::NumericVector root_freqs, Rcpp::NumericVector rate_multipliers);
RcppExport SEXP _MkPrime_singleton_site_prob_jc(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP nTipSEXP, SEXP kStatesSEXP, SEXP root_freqsSEXP, SEXP rate_multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< int >::type kStates(kStatesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type root_freqs(root_freqsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rate_multipliers(rate_multipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(singleton_site_prob_jc(parent, child, edge_length, nTip, kStates, root_freqs, rate_multipliers));
    return rcpp_result_gen;
END_RCPP
}
// constant_site_prob_jc_collapsed
double constant_site_prob_jc_collapsed(Rcpp::IntegerVector parent, Rcpp::IntegerVector child, Rcpp::NumericVector edge_length, int nTip, int kFull, int kObs, Rcpp::NumericVector rate_multipliers);
RcppExport SEXP _MkPrime_constant_site_prob_jc_collapsed(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP nTipSEXP, SEXP kFullSEXP, SEXP kObsSEXP, SEXP rate_multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< int >::type kFull(kFullSEXP);
    Rcpp::traits::input_parameter< int >::type kObs(kObsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rate_multipliers(rate_multipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(constant_site_prob_jc_collapsed(parent, child, edge_length, nTip, kFull, kObs, rate_multipliers));
    return rcpp_result_gen;
END_RCPP
}
// singleton_site_prob_jc_collapsed
double singleton_site_prob_jc_collapsed(Rcpp::IntegerVector parent, Rcpp::IntegerVector child, Rcpp::NumericVector edge_length, int nTip, int kFull, int kObs, Rcpp::NumericVector rate_multipliers);
RcppExport SEXP _MkPrime_singleton_site_prob_jc_collapsed(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP nTipSEXP, SEXP kFullSEXP, SEXP kObsSEXP, SEXP rate_multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< int >::type kFull(kFullSEXP);
    Rcpp::traits::input_parameter< int >::type kObs(kObsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rate_multipliers(rate_multipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(singleton_site_prob_jc_collapsed(parent, child, edge_length, nTip, kFull, kObs, rate_multipliers));
    return rcpp_result_gen;
END_RCPP
}
// constant_site_prob_mkn
double constant_site_prob_mkn(Rcpp::IntegerVector parent, Rcpp::IntegerVector child, Rcpp::NumericVector edge_length, int nTip, double rate_loss, Rcpp::NumericVector root_freqs, Rcpp::NumericVector rate_multipliers);
RcppExport SEXP _MkPrime_constant_site_prob_mkn(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP nTipSEXP, SEXP rate_lossSEXP, SEXP root_freqsSEXP, SEXP rate_multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< double >::type rate_loss(rate_lossSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type root_freqs(root_freqsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rate_multipliers(rate_multipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(constant_site_prob_mkn(parent, child, edge_length, nTip, rate_loss, root_freqs, rate_multipliers));
    return rcpp_result_gen;
END_RCPP
}
// singleton_site_prob_mkn
double singleton_site_prob_mkn(Rcpp::IntegerVector parent, Rcpp::IntegerVector child, Rcpp::NumericVector edge_length, int nTip, double rate_loss, Rcpp::NumericVector root_freqs, Rcpp::NumericVector rate_multipliers);
RcppExport SEXP _MkPrime_singleton_site_prob_mkn(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP nTipSEXP, SEXP rate_lossSEXP, SEXP root_freqsSEXP, SEXP rate_multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< double >::type rate_loss(rate_lossSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type root_freqs(root_freqsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rate_multipliers(rate_multipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(singleton_site_prob_mkn(parent, child, edge_length, nTip, rate_loss, root_freqs, rate_multipliers));
    return rcpp_result_gen;
END_RCPP
}
// mk_prime_relabel_log
double mk_prime_relabel_log(int kPrime, int kObs);
RcppExport SEXP _MkPrime_mk_prime_relabel_log(SEXP kPrimeSEXP, SEXP kObsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kPrime(kPrimeSEXP);
    Rcpp::traits::input_parameter< int >::type kObs(kObsSEXP);
    rcpp_result_gen = Rcpp::wrap(mk_prime_relabel_log(kPrime, kObs));
    return rcpp_result_gen;
END_RCPP
}
// mk_prime_relabel_log_batch
Rcpp::NumericVector mk_prime_relabel_log_batch(Rcpp::IntegerVector kPrime_vec, int kObs);
RcppExport SEXP _MkPrime_mk_prime_relabel_log_batch(SEXP kPrime_vecSEXP, SEXP kObsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type kPrime_vec(kPrime_vecSEXP);
    Rcpp::traits::input_parameter< int >::type kObs(kObsSEXP);
    rcpp_result_gen = Rcpp::wrap(mk_prime_relabel_log_batch(kPrime_vec, kObs));
    return rcpp_result_gen;
END_RCPP
}
// mkp_hello
double mkp_hello();
RcppExport SEXP _MkPrime_mkp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(mkp_hello());
    return rcpp_result_gen;
END_RCPP
}
// pruning_jc
double pruning_jc(Rcpp::IntegerVector parent, Rcpp::IntegerVector child, Rcpp::NumericVector edge_length, Rcpp::IntegerMatrix tip_states, int kStates, Rcpp::NumericVector root_freqs);
RcppExport SEXP _MkPrime_pruning_jc(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP tip_statesSEXP, SEXP kStatesSEXP, SEXP root_freqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< int >::type kStates(kStatesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type root_freqs(root_freqsSEXP);
    rcpp_result_gen = Rcpp::wrap(pruning_jc(parent, child, edge_length, tip_states, kStates, root_freqs));
    return rcpp_result_gen;
END_RCPP
}
// pruning_jc_collapsed
double pruning_jc_collapsed(Rcpp::IntegerVector parent, Rcpp::IntegerVector child, Rcpp::NumericVector edge_length, Rcpp::IntegerMatrix tip_states, int kFull, int kObs);
RcppExport SEXP _MkPrime_pruning_jc_collapsed(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP tip_statesSEXP, SEXP kFullSEXP, SEXP kObsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< int >::type kFull(kFullSEXP);
    Rcpp::traits::input_parameter< int >::type kObs(kObsSEXP);
    rcpp_result_gen = Rcpp::wrap(pruning_jc_collapsed(parent, child, edge_length, tip_states, kFull, kObs));
    return rcpp_result_gen;
END_RCPP
}
// pruning_mkn
double pruning_mkn(Rcpp::IntegerVector parent, Rcpp::IntegerVector child, Rcpp::NumericVector edge_length, Rcpp::IntegerMatrix tip_states, double rate_loss, Rcpp::NumericVector root_freqs);
RcppExport SEXP _MkPrime_pruning_mkn(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP tip_statesSEXP, SEXP rate_lossSEXP, SEXP root_freqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< double >::type rate_loss(rate_lossSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type root_freqs(root_freqsSEXP);
    rcpp_result_gen = Rcpp::wrap(pruning_mkn(parent, child, edge_length, tip_states, rate_loss, root_freqs));
    return rcpp_result_gen;
END_RCPP
}
// f81_transition_cpp
Rcpp::NumericMatrix f81_transition_cpp(Rcpp::NumericMatrix cl, Rcpp::NumericVector pi, double mu, double t);
RcppExport SEXP _MkPrime_f81_transition_cpp(SEXP clSEXP, SEXP piSEXP, SEXP muSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cl(clSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(f81_transition_cpp(cl, pi, mu, t));
    return rcpp_result_gen;
END_RCPP
}
// bactrian_draws
NumericVector bactrian_draws(int n);
RcppExport SEXP _MkPrime_bactrian_draws(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(bactrian_draws(n));
    return rcpp_result_gen;
END_RCPP
}
// bactrian_2d_draws
NumericMatrix bactrian_2d_draws(int n, double rho);
RcppExport SEXP _MkPrime_bactrian_2d_draws(SEXP nSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(bactrian_2d_draws(n, rho));
    return rcpp_result_gen;
END_RCPP
}
// fitch_score_r
int fitch_score_r(IntegerVector parent, IntegerVector child, IntegerMatrix tipStates, int nTip, int kStates);
RcppExport SEXP _MkPrime_fitch_score_r(SEXP parentSEXP, SEXP childSEXP, SEXP tipStatesSEXP, SEXP nTipSEXP, SEXP kStatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type tipStates(tipStatesSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< int >::type kStates(kStatesSEXP);
    rcpp_result_gen = Rcpp::wrap(fitch_score_r(parent, child, tipStates, nTip, kStates));
    return rcpp_result_gen;
END_RCPP
}
// init_mcmc_state
SEXP init_mcmc_state(IntegerVector parent, IntegerVector child, NumericVector relBrLengths, double treeLength, double rateLoss, double rateLogSd, double rateNeo, double p, IntegerVector kPrime, double logLik, double logPrior, double betaScale, double kprimeAlpha, double kprimeBeta, NumericVector classRateLogSd, NumericVector classW, NumericVector classRate, IntegerVector nCharPerClass, double etaNeo, bool useHyperpriorOnSigma, double hyperTau, NumericVector classZ);
RcppExport SEXP _MkPrime_init_mcmc_state(SEXP parentSEXP, SEXP childSEXP, SEXP relBrLengthsSEXP, SEXP treeLengthSEXP, SEXP rateLossSEXP, SEXP rateLogSdSEXP, SEXP rateNeoSEXP, SEXP pSEXP, SEXP kPrimeSEXP, SEXP logLikSEXP, SEXP logPriorSEXP, SEXP betaScaleSEXP, SEXP kprimeAlphaSEXP, SEXP kprimeBetaSEXP, SEXP classRateLogSdSEXP, SEXP classWSEXP, SEXP classRateSEXP, SEXP nCharPerClassSEXP, SEXP etaNeoSEXP, SEXP useHyperpriorOnSigmaSEXP, SEXP hyperTauSEXP, SEXP classZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type relBrLengths(relBrLengthsSEXP);
    Rcpp::traits::input_parameter< double >::type treeLength(treeLengthSEXP);
    Rcpp::traits::input_parameter< double >::type rateLoss(rateLossSEXP);
    Rcpp::traits::input_parameter< double >::type rateLogSd(rateLogSdSEXP);
    Rcpp::traits::input_parameter< double >::type rateNeo(rateNeoSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type kPrime(kPrimeSEXP);
    Rcpp::traits::input_parameter< double >::type logLik(logLikSEXP);
    Rcpp::traits::input_parameter< double >::type logPrior(logPriorSEXP);
    Rcpp::traits::input_parameter< double >::type betaScale(betaScaleSEXP);
    Rcpp::traits::input_parameter< double >::type kprimeAlpha(kprimeAlphaSEXP);
    Rcpp::traits::input_parameter< double >::type kprimeBeta(kprimeBetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type classRateLogSd(classRateLogSdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type classW(classWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type classRate(classRateSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nCharPerClass(nCharPerClassSEXP);
    Rcpp::traits::input_parameter< double >::type etaNeo(etaNeoSEXP);
    Rcpp::traits::input_parameter< bool >::type useHyperpriorOnSigma(useHyperpriorOnSigmaSEXP);
    Rcpp::traits::input_parameter< double >::type hyperTau(hyperTauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type classZ(classZSEXP);
    rcpp_result_gen = Rcpp::wrap(init_mcmc_state(parent, child, relBrLengths, treeLength, rateLoss, rateLogSd, rateNeo, p, kPrime, logLik, logPrior, betaScale, kprimeAlpha, kprimeBeta, classRateLogSd, classW, classRate, nCharPerClass, etaNeo, useHyperpriorOnSigma, hyperTau, classZ));
    return rcpp_result_gen;
END_RCPP
}
// fill_partition_cache
void fill_partition_cache(SEXP dataPtr, SEXP statePtr);
RcppExport SEXP _MkPrime_fill_partition_cache(SEXP dataPtrSEXP, SEXP statePtrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    fill_partition_cache(dataPtr, statePtr);
    return R_NilValue;
END_RCPP
}
// allocate_cl_workspace
void allocate_cl_workspace(SEXP dataPtr, SEXP statePtr);
RcppExport SEXP _MkPrime_allocate_cl_workspace(SEXP dataPtrSEXP, SEXP statePtrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    allocate_cl_workspace(dataPtr, statePtr);
    return R_NilValue;
END_RCPP
}
// get_mcmc_state
List get_mcmc_state(SEXP statePtr);
RcppExport SEXP _MkPrime_get_mcmc_state(SEXP statePtrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    rcpp_result_gen = Rcpp::wrap(get_mcmc_state(statePtr));
    return rcpp_result_gen;
END_RCPP
}
// compute_topo_hash
double compute_topo_hash(IntegerVector parent, IntegerVector child, int nTip);
RcppExport SEXP _MkPrime_compute_topo_hash(SEXP parentSEXP, SEXP childSEXP, SEXP nTipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_topo_hash(parent, child, nTip));
    return rcpp_result_gen;
END_RCPP
}
// get_state_log_lik
double get_state_log_lik(SEXP statePtr);
RcppExport SEXP _MkPrime_get_state_log_lik(SEXP statePtrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    rcpp_result_gen = Rcpp::wrap(get_state_log_lik(statePtr));
    return rcpp_result_gen;
END_RCPP
}
// get_marginal_cache_state
List get_marginal_cache_state(SEXP statePtr);
RcppExport SEXP _MkPrime_get_marginal_cache_state(SEXP statePtrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    rcpp_result_gen = Rcpp::wrap(get_marginal_cache_state(statePtr));
    return rcpp_result_gen;
END_RCPP
}
// invalidate_marginal_cache
void invalidate_marginal_cache(SEXP statePtr);
RcppExport SEXP _MkPrime_invalidate_marginal_cache(SEXP statePtrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    invalidate_marginal_cache(statePtr);
    return R_NilValue;
END_RCPP
}
// eval_log_prior_cpp
double eval_log_prior_cpp(SEXP dataPtr, SEXP statePtr);
RcppExport SEXP _MkPrime_eval_log_prior_cpp(SEXP dataPtrSEXP, SEXP statePtrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_log_prior_cpp(dataPtr, statePtr));
    return rcpp_result_gen;
END_RCPP
}
// eval_log_prior_partitioned_cpp
double eval_log_prior_partitioned_cpp(SEXP dataPtr, SEXP statePtr, Rcpp::NumericVector classRateLogSd, Rcpp::NumericVector classW, double etaNeo, bool useHyperpriorOnSigma, double hyperTau, Rcpp::NumericVector classZ);
RcppExport SEXP _MkPrime_eval_log_prior_partitioned_cpp(SEXP dataPtrSEXP, SEXP statePtrSEXP, SEXP classRateLogSdSEXP, SEXP classWSEXP, SEXP etaNeoSEXP, SEXP useHyperpriorOnSigmaSEXP, SEXP hyperTauSEXP, SEXP classZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type classRateLogSd(classRateLogSdSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type classW(classWSEXP);
    Rcpp::traits::input_parameter< double >::type etaNeo(etaNeoSEXP);
    Rcpp::traits::input_parameter< bool >::type useHyperpriorOnSigma(useHyperpriorOnSigmaSEXP);
    Rcpp::traits::input_parameter< double >::type hyperTau(hyperTauSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type classZ(classZSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_log_prior_partitioned_cpp(dataPtr, statePtr, classRateLogSd, classW, etaNeo, useHyperpriorOnSigma, hyperTau, classZ));
    return rcpp_result_gen;
END_RCPP
}
// set_class_rate_concentration
void set_class_rate_concentration(SEXP dataPtr, double concentration);
RcppExport SEXP _MkPrime_set_class_rate_concentration(SEXP dataPtrSEXP, SEXP concentrationSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< double >::type concentration(concentrationSEXP);
    set_class_rate_concentration(dataPtr, concentration);
    return R_NilValue;
END_RCPP
}
// eval_full_loglik_cpp
double eval_full_loglik_cpp(SEXP dataPtr, SEXP statePtr);
RcppExport SEXP _MkPrime_eval_full_loglik_cpp(SEXP dataPtrSEXP, SEXP statePtrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_full_loglik_cpp(dataPtr, statePtr));
    return rcpp_result_gen;
END_RCPP
}
// eval_full_loglik_at_cpp
double eval_full_loglik_at_cpp(SEXP dataPtr, SEXP statePtr, IntegerVector parent, IntegerVector child, NumericVector edgeLen);
RcppExport SEXP _MkPrime_eval_full_loglik_at_cpp(SEXP dataPtrSEXP, SEXP statePtrSEXP, SEXP parentSEXP, SEXP childSEXP, SEXP edgeLenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edgeLen(edgeLenSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_full_loglik_at_cpp(dataPtr, statePtr, parent, child, edgeLen));
    return rcpp_result_gen;
END_RCPP
}
// eval_preorder_paths_cpp
NumericVector eval_preorder_paths_cpp(SEXP dataPtr, SEXP statePtr, IntegerVector parent, IntegerVector child, NumericVector edgeLen);
RcppExport SEXP _MkPrime_eval_preorder_paths_cpp(SEXP dataPtrSEXP, SEXP statePtrSEXP, SEXP parentSEXP, SEXP childSEXP, SEXP edgeLenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edgeLen(edgeLenSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_preorder_paths_cpp(dataPtr, statePtr, parent, child, edgeLen));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_spr_enumerate_cpp
List gibbs_spr_enumerate_cpp(SEXP dataPtr, SEXP statePtr, int pruneRow);
RcppExport SEXP _MkPrime_gibbs_spr_enumerate_cpp(SEXP dataPtrSEXP, SEXP statePtrSEXP, SEXP pruneRowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    Rcpp::traits::input_parameter< int >::type pruneRow(pruneRowSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_spr_enumerate_cpp(dataPtr, statePtr, pruneRow));
    return rcpp_result_gen;
END_RCPP
}
// bin_mixture_log_density
double bin_mixture_log_density(NumericVector weights, double f, int nBins);
RcppExport SEXP _MkPrime_bin_mixture_log_density(SEXP weightsSEXP, SEXP fSEXP, SEXP nBinsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type f(fSEXP);
    Rcpp::traits::input_parameter< int >::type nBins(nBinsSEXP);
    rcpp_result_gen = Rcpp::wrap(bin_mixture_log_density(weights, f, nBins));
    return rcpp_result_gen;
END_RCPP
}
// kprime_sweep_candidates
IntegerVector kprime_sweep_candidates(SEXP dataPtr, SEXP statePtr, double beta);
RcppExport SEXP _MkPrime_kprime_sweep_candidates(SEXP dataPtrSEXP, SEXP statePtrSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(kprime_sweep_candidates(dataPtr, statePtr, beta));
    return rcpp_result_gen;
END_RCPP
}
// do_move_cpp
bool do_move_cpp(SEXP dataPtr, SEXP statePtr, int moveType, int charIdx, double scaleTuning, double betaSimplexTuning, int intWalkWindow, double beta);
RcppExport SEXP _MkPrime_do_move_cpp(SEXP dataPtrSEXP, SEXP statePtrSEXP, SEXP moveTypeSEXP, SEXP charIdxSEXP, SEXP scaleTuningSEXP, SEXP betaSimplexTuningSEXP, SEXP intWalkWindowSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    Rcpp::traits::input_parameter< int >::type moveType(moveTypeSEXP);
    Rcpp::traits::input_parameter< int >::type charIdx(charIdxSEXP);
    Rcpp::traits::input_parameter< double >::type scaleTuning(scaleTuningSEXP);
    Rcpp::traits::input_parameter< double >::type betaSimplexTuning(betaSimplexTuningSEXP);
    Rcpp::traits::input_parameter< int >::type intWalkWindow(intWalkWindowSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(do_move_cpp(dataPtr, statePtr, moveType, charIdx, scaleTuning, betaSimplexTuning, intWalkWindow, beta));
    return rcpp_result_gen;
END_RCPP
}
// run_mcmc_batch_cpp
List run_mcmc_batch_cpp(SEXP dataPtr, List stateXPtrs, NumericVector betas, IntegerVector moveTypeCodes, IntegerVector transIdxCpp, IntegerVector sliceParamCodes, NumericVector moveWeights, NumericMatrix chainScaleTunings, NumericVector chainBsmpTunings, IntegerVector chainIntWalkWins, IntegerVector moveIntParams, NumericMatrix sliceWidths, NumericMatrix jointRhos, int nBatch, int startIter, int warmup, int thin, bool hasNeo, int nEdge, double cacheBonus);
RcppExport SEXP _MkPrime_run_mcmc_batch_cpp(SEXP dataPtrSEXP, SEXP stateXPtrsSEXP, SEXP betasSEXP, SEXP moveTypeCodesSEXP, SEXP transIdxCppSEXP, SEXP sliceParamCodesSEXP, SEXP moveWeightsSEXP, SEXP chainScaleTuningsSEXP, SEXP chainBsmpTuningsSEXP, SEXP chainIntWalkWinsSEXP, SEXP moveIntParamsSEXP, SEXP sliceWidthsSEXP, SEXP jointRhosSEXP, SEXP nBatchSEXP, SEXP startIterSEXP, SEXP warmupSEXP, SEXP thinSEXP, SEXP hasNeoSEXP, SEXP nEdgeSEXP, SEXP cacheBonusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< List >::type stateXPtrs(stateXPtrsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type moveTypeCodes(moveTypeCodesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type transIdxCpp(transIdxCppSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sliceParamCodes(sliceParamCodesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type moveWeights(moveWeightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type chainScaleTunings(chainScaleTuningsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type chainBsmpTunings(chainBsmpTuningsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type chainIntWalkWins(chainIntWalkWinsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type moveIntParams(moveIntParamsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sliceWidths(sliceWidthsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type jointRhos(jointRhosSEXP);
    Rcpp::traits::input_parameter< int >::type nBatch(nBatchSEXP);
    Rcpp::traits::input_parameter< int >::type startIter(startIterSEXP);
    Rcpp::traits::input_parameter< int >::type warmup(warmupSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< bool >::type hasNeo(hasNeoSEXP);
    Rcpp::traits::input_parameter< int >::type nEdge(nEdgeSEXP);
    Rcpp::traits::input_parameter< double >::type cacheBonus(cacheBonusSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mcmc_batch_cpp(dataPtr, stateXPtrs, betas, moveTypeCodes, transIdxCpp, sliceParamCodes, moveWeights, chainScaleTunings, chainBsmpTunings, chainIntWalkWins, moveIntParams, sliceWidths, jointRhos, nBatch, startIter, warmup, thin, hasNeo, nEdge, cacheBonus));
    return rcpp_result_gen;
END_RCPP
}
// debug_mcmc_data
List debug_mcmc_data(SEXP dataPtr);
RcppExport SEXP _MkPrime_debug_mcmc_data(SEXP dataPtrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    rcpp_result_gen = Rcpp::wrap(debug_mcmc_data(dataPtr));
    return rcpp_result_gen;
END_RCPP
}
// validate_swap_partial_cl
DataFrame validate_swap_partial_cl(SEXP dataPtr, SEXP statePtr, int nodeA);
RcppExport SEXP _MkPrime_validate_swap_partial_cl(SEXP dataPtrSEXP, SEXP statePtrSEXP, SEXP nodeASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type statePtr(statePtrSEXP);
    Rcpp::traits::input_parameter< int >::type nodeA(nodeASEXP);
    rcpp_result_gen = Rcpp::wrap(validate_swap_partial_cl(dataPtr, statePtr, nodeA));
    return rcpp_result_gen;
END_RCPP
}
// test_persite_uncollapsed
Rcpp::NumericVector test_persite_uncollapsed(IntegerVector parent, IntegerVector child, NumericVector edge_length, IntegerMatrix tip_states, int kStates, NumericVector rate_multipliers);
RcppExport SEXP _MkPrime_test_persite_uncollapsed(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP tip_statesSEXP, SEXP kStatesSEXP, SEXP rate_multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< int >::type kStates(kStatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rate_multipliers(rate_multipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(test_persite_uncollapsed(parent, child, edge_length, tip_states, kStates, rate_multipliers));
    return rcpp_result_gen;
END_RCPP
}
// test_persite_collapsed
Rcpp::NumericVector test_persite_collapsed(IntegerVector parent, IntegerVector child, NumericVector edge_length, IntegerMatrix tip_states, int kFull, int kObs, NumericVector rate_multipliers);
RcppExport SEXP _MkPrime_test_persite_collapsed(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP tip_statesSEXP, SEXP kFullSEXP, SEXP kObsSEXP, SEXP rate_multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< int >::type kFull(kFullSEXP);
    Rcpp::traits::input_parameter< int >::type kObs(kObsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rate_multipliers(rate_multipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(test_persite_collapsed(parent, child, edge_length, tip_states, kFull, kObs, rate_multipliers));
    return rcpp_result_gen;
END_RCPP
}
// test_flat_jc_uncollapsed
double test_flat_jc_uncollapsed(IntegerVector parent, IntegerVector child, NumericVector edge_length, IntegerMatrix tip_states, int kStates, bool acrv, NumericVector rate_multipliers);
RcppExport SEXP _MkPrime_test_flat_jc_uncollapsed(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP tip_statesSEXP, SEXP kStatesSEXP, SEXP acrvSEXP, SEXP rate_multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< int >::type kStates(kStatesSEXP);
    Rcpp::traits::input_parameter< bool >::type acrv(acrvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rate_multipliers(rate_multipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(test_flat_jc_uncollapsed(parent, child, edge_length, tip_states, kStates, acrv, rate_multipliers));
    return rcpp_result_gen;
END_RCPP
}
// test_flat_jc_collapsed
double test_flat_jc_collapsed(IntegerVector parent, IntegerVector child, NumericVector edge_length, IntegerMatrix tip_states, int kFull, int kObs, bool acrv, NumericVector rate_multipliers);
RcppExport SEXP _MkPrime_test_flat_jc_collapsed(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP tip_statesSEXP, SEXP kFullSEXP, SEXP kObsSEXP, SEXP acrvSEXP, SEXP rate_multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< int >::type kFull(kFullSEXP);
    Rcpp::traits::input_parameter< int >::type kObs(kObsSEXP);
    Rcpp::traits::input_parameter< bool >::type acrv(acrvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rate_multipliers(rate_multipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(test_flat_jc_collapsed(parent, child, edge_length, tip_states, kFull, kObs, acrv, rate_multipliers));
    return rcpp_result_gen;
END_RCPP
}
// test_flat_jc_constprob_pair
Rcpp::List test_flat_jc_constprob_pair(IntegerVector parent, IntegerVector child, NumericVector edge_length, IntegerMatrix tip_states, int kFull, int kObs, bool acrv, NumericVector rate_multipliers);
RcppExport SEXP _MkPrime_test_flat_jc_constprob_pair(SEXP parentSEXP, SEXP childSEXP, SEXP edge_lengthSEXP, SEXP tip_statesSEXP, SEXP kFullSEXP, SEXP kObsSEXP, SEXP acrvSEXP, SEXP rate_multipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< int >::type kFull(kFullSEXP);
    Rcpp::traits::input_parameter< int >::type kObs(kObsSEXP);
    Rcpp::traits::input_parameter< bool >::type acrv(acrvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rate_multipliers(rate_multipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(test_flat_jc_constprob_pair(parent, child, edge_length, tip_states, kFull, kObs, acrv, rate_multipliers));
    return rcpp_result_gen;
END_RCPP
}
// het_const_site_prob
double het_const_site_prob(IntegerVector parent, IntegerVector child, NumericVector edgeLength, int nTip, int kStates, double baseRateLoss, NumericVector betaBins, NumericVector rateMultipliers);
RcppExport SEXP _MkPrime_het_const_site_prob(SEXP parentSEXP, SEXP childSEXP, SEXP edgeLengthSEXP, SEXP nTipSEXP, SEXP kStatesSEXP, SEXP baseRateLossSEXP, SEXP betaBinsSEXP, SEXP rateMultipliersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edgeLength(edgeLengthSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< int >::type kStates(kStatesSEXP);
    Rcpp::traits::input_parameter< double >::type baseRateLoss(baseRateLossSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaBins(betaBinsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rateMultipliers(rateMultipliersSEXP);
    rcpp_result_gen = Rcpp::wrap(het_const_site_prob(parent, child, edgeLength, nTip, kStates, baseRateLoss, betaBins, rateMultipliers));
    return rcpp_result_gen;
END_RCPP
}
// prepare_mcmc_data
SEXP prepare_mcmc_data(List partitions_r, IntegerVector kObs_r, CharacterVector charTypes_r, bool hasNeo, int nCat, std::string codingStr, bool relabelFlag, double treeLengthShape, double treeLengthRate, double rateLossMeanlog, double rateLossSdlog, double rateLogSdShape, double rateLogSdRate, double rateNeoMeanlog, double rateNeoSdlog, double kprimeHyperA, double kprimeHyperB, bool kPriorLogseries, double kprimeLogseriesC, bool kPriorBetaGeometric, bool qHeterogeneity, int nBetaCat, double betaScaleShape, double betaScaleRate, bool kPriorEmpiricalGeometric, NumericVector empLogBody, int empTailStartK, double empTailDecay, double empLogTailStartP, bool marginalK, bool unconditionalPrior);
RcppExport SEXP _MkPrime_prepare_mcmc_data(SEXP partitions_rSEXP, SEXP kObs_rSEXP, SEXP charTypes_rSEXP, SEXP hasNeoSEXP, SEXP nCatSEXP, SEXP codingStrSEXP, SEXP relabelFlagSEXP, SEXP treeLengthShapeSEXP, SEXP treeLengthRateSEXP, SEXP rateLossMeanlogSEXP, SEXP rateLossSdlogSEXP, SEXP rateLogSdShapeSEXP, SEXP rateLogSdRateSEXP, SEXP rateNeoMeanlogSEXP, SEXP rateNeoSdlogSEXP, SEXP kprimeHyperASEXP, SEXP kprimeHyperBSEXP, SEXP kPriorLogseriesSEXP, SEXP kprimeLogseriesCSEXP, SEXP kPriorBetaGeometricSEXP, SEXP qHeterogeneitySEXP, SEXP nBetaCatSEXP, SEXP betaScaleShapeSEXP, SEXP betaScaleRateSEXP, SEXP kPriorEmpiricalGeometricSEXP, SEXP empLogBodySEXP, SEXP empTailStartKSEXP, SEXP empTailDecaySEXP, SEXP empLogTailStartPSEXP, SEXP marginalKSEXP, SEXP unconditionalPriorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type partitions_r(partitions_rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type kObs_r(kObs_rSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type charTypes_r(charTypes_rSEXP);
    Rcpp::traits::input_parameter< bool >::type hasNeo(hasNeoSEXP);
    Rcpp::traits::input_parameter< int >::type nCat(nCatSEXP);
    Rcpp::traits::input_parameter< std::string >::type codingStr(codingStrSEXP);
    Rcpp::traits::input_parameter< bool >::type relabelFlag(relabelFlagSEXP);
    Rcpp::traits::input_parameter< double >::type treeLengthShape(treeLengthShapeSEXP);
    Rcpp::traits::input_parameter< double >::type treeLengthRate(treeLengthRateSEXP);
    Rcpp::traits::input_parameter< double >::type rateLossMeanlog(rateLossMeanlogSEXP);
    Rcpp::traits::input_parameter< double >::type rateLossSdlog(rateLossSdlogSEXP);
    Rcpp::traits::input_parameter< double >::type rateLogSdShape(rateLogSdShapeSEXP);
    Rcpp::traits::input_parameter< double >::type rateLogSdRate(rateLogSdRateSEXP);
    Rcpp::traits::input_parameter< double >::type rateNeoMeanlog(rateNeoMeanlogSEXP);
    Rcpp::traits::input_parameter< double >::type rateNeoSdlog(rateNeoSdlogSEXP);
    Rcpp::traits::input_parameter< double >::type kprimeHyperA(kprimeHyperASEXP);
    Rcpp::traits::input_parameter< double >::type kprimeHyperB(kprimeHyperBSEXP);
    Rcpp::traits::input_parameter< bool >::type kPriorLogseries(kPriorLogseriesSEXP);
    Rcpp::traits::input_parameter< double >::type kprimeLogseriesC(kprimeLogseriesCSEXP);
    Rcpp::traits::input_parameter< bool >::type kPriorBetaGeometric(kPriorBetaGeometricSEXP);
    Rcpp::traits::input_parameter< bool >::type qHeterogeneity(qHeterogeneitySEXP);
    Rcpp::traits::input_parameter< int >::type nBetaCat(nBetaCatSEXP);
    Rcpp::traits::input_parameter< double >::type betaScaleShape(betaScaleShapeSEXP);
    Rcpp::traits::input_parameter< double >::type betaScaleRate(betaScaleRateSEXP);
    Rcpp::traits::input_parameter< bool >::type kPriorEmpiricalGeometric(kPriorEmpiricalGeometricSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type empLogBody(empLogBodySEXP);
    Rcpp::traits::input_parameter< int >::type empTailStartK(empTailStartKSEXP);
    Rcpp::traits::input_parameter< double >::type empTailDecay(empTailDecaySEXP);
    Rcpp::traits::input_parameter< double >::type empLogTailStartP(empLogTailStartPSEXP);
    Rcpp::traits::input_parameter< bool >::type marginalK(marginalKSEXP);
    Rcpp::traits::input_parameter< bool >::type unconditionalPrior(unconditionalPriorSEXP);
    rcpp_result_gen = Rcpp::wrap(prepare_mcmc_data(partitions_r, kObs_r, charTypes_r, hasNeo, nCat, codingStr, relabelFlag, treeLengthShape, treeLengthRate, rateLossMeanlog, rateLossSdlog, rateLogSdShape, rateLogSdRate, rateNeoMeanlog, rateNeoSdlog, kprimeHyperA, kprimeHyperB, kPriorLogseries, kprimeLogseriesC, kPriorBetaGeometric, qHeterogeneity, nBetaCat, betaScaleShape, betaScaleRate, kPriorEmpiricalGeometric, empLogBody, empTailStartK, empTailDecay, empLogTailStartP, marginalK, unconditionalPrior));
    return rcpp_result_gen;
END_RCPP
}
// set_branch_bins
void set_branch_bins(SEXP dataPtr, int nBins);
RcppExport SEXP _MkPrime_set_branch_bins(SEXP dataPtrSEXP, SEXP nBinsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< int >::type nBins(nBinsSEXP);
    set_branch_bins(dataPtr, nBins);
    return R_NilValue;
END_RCPP
}
// set_kprime_trunc_k
void set_kprime_trunc_k(SEXP dataPtr, int K);
RcppExport SEXP _MkPrime_set_kprime_trunc_k(SEXP dataPtrSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    set_kprime_trunc_k(dataPtr, K);
    return R_NilValue;
END_RCPP
}
// cpp_log_likelihood_xptr
double cpp_log_likelihood_xptr(SEXP dataPtr, Rcpp::IntegerVector parent, Rcpp::IntegerVector child, Rcpp::NumericVector edgeLen, Rcpp::IntegerVector kPrime, double rateLoss, double rateLogSd, double rateNeo, double betaScale);
RcppExport SEXP _MkPrime_cpp_log_likelihood_xptr(SEXP dataPtrSEXP, SEXP parentSEXP, SEXP childSEXP, SEXP edgeLenSEXP, SEXP kPrimeSEXP, SEXP rateLossSEXP, SEXP rateLogSdSEXP, SEXP rateNeoSEXP, SEXP betaScaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edgeLen(edgeLenSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type kPrime(kPrimeSEXP);
    Rcpp::traits::input_parameter< double >::type rateLoss(rateLossSEXP);
    Rcpp::traits::input_parameter< double >::type rateLogSd(rateLogSdSEXP);
    Rcpp::traits::input_parameter< double >::type rateNeo(rateNeoSEXP);
    Rcpp::traits::input_parameter< double >::type betaScale(betaScaleSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_log_likelihood_xptr(dataPtr, parent, child, edgeLen, kPrime, rateLoss, rateLogSd, rateNeo, betaScale));
    return rcpp_result_gen;
END_RCPP
}
// cpp_log_likelihood_partitioned_xptr
double cpp_log_likelihood_partitioned_xptr(SEXP dataPtr, Rcpp::IntegerVector parent, Rcpp::IntegerVector child, Rcpp::NumericVector edgeLen, Rcpp::IntegerVector kPrime, double rateLoss, Rcpp::NumericVector rateLogSd, Rcpp::NumericVector classRate, double etaNeo, double betaScale);
RcppExport SEXP _MkPrime_cpp_log_likelihood_partitioned_xptr(SEXP dataPtrSEXP, SEXP parentSEXP, SEXP childSEXP, SEXP edgeLenSEXP, SEXP kPrimeSEXP, SEXP rateLossSEXP, SEXP rateLogSdSEXP, SEXP classRateSEXP, SEXP etaNeoSEXP, SEXP betaScaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type edgeLen(edgeLenSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type kPrime(kPrimeSEXP);
    Rcpp::traits::input_parameter< double >::type rateLoss(rateLossSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rateLogSd(rateLogSdSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type classRate(classRateSEXP);
    Rcpp::traits::input_parameter< double >::type etaNeo(etaNeoSEXP);
    Rcpp::traits::input_parameter< double >::type betaScale(betaScaleSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_log_likelihood_partitioned_xptr(dataPtr, parent, child, edgeLen, kPrime, rateLoss, rateLogSd, classRate, etaNeo, betaScale));
    return rcpp_result_gen;
END_RCPP
}
// cpp_data_nclasses
int cpp_data_nclasses(SEXP dataPtr);
RcppExport SEXP _MkPrime_cpp_data_nclasses(SEXP dataPtrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dataPtr(dataPtrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_data_nclasses(dataPtr));
    return rcpp_result_gen;
END_RCPP
}
// spr_proposal
List spr_proposal(IntegerMatrix edge, int nTip, double treeLength, NumericVector relBrLengths);
RcppExport SEXP _MkPrime_spr_proposal(SEXP edgeSEXP, SEXP nTipSEXP, SEXP treeLengthSEXP, SEXP relBrLengthsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< double >::type treeLength(treeLengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type relBrLengths(relBrLengthsSEXP);
    rcpp_result_gen = Rcpp::wrap(spr_proposal(edge, nTip, treeLength, relBrLengths));
    return rcpp_result_gen;
END_RCPP
}
// beta_simplex_proposal
List beta_simplex_proposal(NumericVector x, int index, double tuning);
RcppExport SEXP _MkPrime_beta_simplex_proposal(SEXP xSEXP, SEXP indexSEXP, SEXP tuningSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< double >::type tuning(tuningSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_simplex_proposal(x, index, tuning));
    return rcpp_result_gen;
END_RCPP
}
// dirichlet_simplex_proposal
List dirichlet_simplex_proposal(NumericVector x, int nCats, double alpha);
RcppExport SEXP _MkPrime_dirichlet_simplex_proposal(SEXP xSEXP, SEXP nCatsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nCats(nCatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(dirichlet_simplex_proposal(x, nCats, alpha));
    return rcpp_result_gen;
END_RCPP
}
// local_dirichlet_proposal
List local_dirichlet_proposal(NumericVector x, IntegerVector parent, IntegerVector child, int nCats, double alpha);
RcppExport SEXP _MkPrime_local_dirichlet_proposal(SEXP xSEXP, SEXP parentSEXP, SEXP childSEXP, SEXP nCatsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child(childSEXP);
    Rcpp::traits::input_parameter< int >::type nCats(nCatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(local_dirichlet_proposal(x, parent, child, nCats, alpha));
    return rcpp_result_gen;
END_RCPP
}
// jc_transition_probs
Rcpp::NumericMatrix jc_transition_probs(int k, double t);
RcppExport SEXP _MkPrime_jc_transition_probs(SEXP kSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(jc_transition_probs(k, t));
    return rcpp_result_gen;
END_RCPP
}
// mkn_transition_probs
Rcpp::NumericMatrix mkn_transition_probs(double rate_loss, double t);
RcppExport SEXP _MkPrime_mkn_transition_probs(SEXP rate_lossSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rate_loss(rate_lossSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(mkn_transition_probs(rate_loss, t));
    return rcpp_result_gen;
END_RCPP
}
// mkn_stationary_freqs
Rcpp::NumericVector mkn_stationary_freqs(double rate_loss);
RcppExport SEXP _MkPrime_mkn_stationary_freqs(SEXP rate_lossSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rate_loss(rate_lossSEXP);
    rcpp_result_gen = Rcpp::wrap(mkn_stationary_freqs(rate_loss));
    return rcpp_result_gen;
END_RCPP
}
// frechet_correlation_ess_cpp
double frechet_correlation_ess_cpp(const NumericMatrix& dmat_sq, int min_nsamples);
RcppExport SEXP _MkPrime_frechet_correlation_ess_cpp(SEXP dmat_sqSEXP, SEXP min_nsamplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type dmat_sq(dmat_sqSEXP);
    Rcpp::traits::input_parameter< int >::type min_nsamples(min_nsamplesSEXP);
    rcpp_result_gen = Rcpp::wrap(frechet_correlation_ess_cpp(dmat_sq, min_nsamples));
    return rcpp_result_gen;
END_RCPP
}
// median_pseudo_ess_cpp
double median_pseudo_ess_cpp(const NumericMatrix& dmat, int min_nsamples, int max_rows);
RcppExport SEXP _MkPrime_median_pseudo_ess_cpp(SEXP dmatSEXP, SEXP min_nsamplesSEXP, SEXP max_rowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< int >::type min_nsamples(min_nsamplesSEXP);
    Rcpp::traits::input_parameter< int >::type max_rows(max_rowsSEXP);
    rcpp_result_gen = Rcpp::wrap(median_pseudo_ess_cpp(dmat, min_nsamples, max_rows));
    return rcpp_result_gen;
END_RCPP
}
// tbr_proposal
List tbr_proposal(IntegerMatrix edge, int nTip, double treeLength, NumericVector relBrLengths);
RcppExport SEXP _MkPrime_tbr_proposal(SEXP edgeSEXP, SEXP nTipSEXP, SEXP treeLengthSEXP, SEXP relBrLengthsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< double >::type treeLength(treeLengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type relBrLengths(relBrLengthsSEXP);
    rcpp_result_gen = Rcpp::wrap(tbr_proposal(edge, nTip, treeLength, relBrLengths));
    return rcpp_result_gen;
END_RCPP
}
// swap_subtrees_cpp
List swap_subtrees_cpp(IntegerMatrix edge, int nTip, double treeLength, NumericVector relBrLengths, int nodeA, int nodeB);
RcppExport SEXP _MkPrime_swap_subtrees_cpp(SEXP edgeSEXP, SEXP nTipSEXP, SEXP treeLengthSEXP, SEXP relBrLengthsSEXP, SEXP nodeASEXP, SEXP nodeBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< double >::type treeLength(treeLengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type relBrLengths(relBrLengthsSEXP);
    Rcpp::traits::input_parameter< int >::type nodeA(nodeASEXP);
    Rcpp::traits::input_parameter< int >::type nodeB(nodeBSEXP);
    rcpp_result_gen = Rcpp::wrap(swap_subtrees_cpp(edge, nTip, treeLength, relBrLengths, nodeA, nodeB));
    return rcpp_result_gen;
END_RCPP
}
// get_valid_swap_partners_cpp
IntegerVector get_valid_swap_partners_cpp(IntegerMatrix edge, int nTip, int pruneNode);
RcppExport SEXP _MkPrime_get_valid_swap_partners_cpp(SEXP edgeSEXP, SEXP nTipSEXP, SEXP pruneNodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< int >::type pruneNode(pruneNodeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_valid_swap_partners_cpp(edge, nTip, pruneNode));
    return rcpp_result_gen;
END_RCPP
}
// nni_proposal
List nni_proposal(IntegerMatrix edge, int nTip, double treeLength, NumericVector relBrLengths);
RcppExport SEXP _MkPrime_nni_proposal(SEXP edgeSEXP, SEXP nTipSEXP, SEXP treeLengthSEXP, SEXP relBrLengthsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< double >::type treeLength(treeLengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type relBrLengths(relBrLengthsSEXP);
    rcpp_result_gen = Rcpp::wrap(nni_proposal(edge, nTip, treeLength, relBrLengths));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MkPrime_pruning_jc_acrv", (DL_FUNC) &_MkPrime_pruning_jc_acrv, 7},
    {"_MkPrime_pruning_jc_acrv_collapsed", (DL_FUNC) &_MkPrime_pruning_jc_acrv_collapsed, 7},
    {"_MkPrime_pruning_mkn_acrv", (DL_FUNC) &_MkPrime_pruning_mkn_acrv, 7},
    {"_MkPrime_constant_site_prob_jc", (DL_FUNC) &_MkPrime_constant_site_prob_jc, 7},
    {"_MkPrime_singleton_site_prob_jc", (DL_FUNC) &_MkPrime_singleton_site_prob_jc, 7},
    {"_MkPrime_constant_site_prob_jc_collapsed", (DL_FUNC) &_MkPrime_constant_site_prob_jc_collapsed, 7},
    {"_MkPrime_singleton_site_prob_jc_collapsed", (DL_FUNC) &_MkPrime_singleton_site_prob_jc_collapsed, 7},
    {"_MkPrime_constant_site_prob_mkn", (DL_FUNC) &_MkPrime_constant_site_prob_mkn, 7},
    {"_MkPrime_singleton_site_prob_mkn", (DL_FUNC) &_MkPrime_singleton_site_prob_mkn, 7},
    {"_MkPrime_mk_prime_relabel_log", (DL_FUNC) &_MkPrime_mk_prime_relabel_log, 2},
    {"_MkPrime_mk_prime_relabel_log_batch", (DL_FUNC) &_MkPrime_mk_prime_relabel_log_batch, 2},
    {"_MkPrime_mkp_hello", (DL_FUNC) &_MkPrime_mkp_hello, 0},
    {"_MkPrime_pruning_jc", (DL_FUNC) &_MkPrime_pruning_jc, 6},
    {"_MkPrime_pruning_jc_collapsed", (DL_FUNC) &_MkPrime_pruning_jc_collapsed, 6},
    {"_MkPrime_pruning_mkn", (DL_FUNC) &_MkPrime_pruning_mkn, 6},
    {"_MkPrime_f81_transition_cpp", (DL_FUNC) &_MkPrime_f81_transition_cpp, 4},
    {"_MkPrime_bactrian_draws", (DL_FUNC) &_MkPrime_bactrian_draws, 1},
    {"_MkPrime_bactrian_2d_draws", (DL_FUNC) &_MkPrime_bactrian_2d_draws, 2},
    {"_MkPrime_fitch_score_r", (DL_FUNC) &_MkPrime_fitch_score_r, 5},
    {"_MkPrime_init_mcmc_state", (DL_FUNC) &_MkPrime_init_mcmc_state, 22},
    {"_MkPrime_fill_partition_cache", (DL_FUNC) &_MkPrime_fill_partition_cache, 2},
    {"_MkPrime_allocate_cl_workspace", (DL_FUNC) &_MkPrime_allocate_cl_workspace, 2},
    {"_MkPrime_get_mcmc_state", (DL_FUNC) &_MkPrime_get_mcmc_state, 1},
    {"_MkPrime_compute_topo_hash", (DL_FUNC) &_MkPrime_compute_topo_hash, 3},
    {"_MkPrime_get_state_log_lik", (DL_FUNC) &_MkPrime_get_state_log_lik, 1},
    {"_MkPrime_get_marginal_cache_state", (DL_FUNC) &_MkPrime_get_marginal_cache_state, 1},
    {"_MkPrime_invalidate_marginal_cache", (DL_FUNC) &_MkPrime_invalidate_marginal_cache, 1},
    {"_MkPrime_eval_log_prior_cpp", (DL_FUNC) &_MkPrime_eval_log_prior_cpp, 2},
    {"_MkPrime_eval_log_prior_partitioned_cpp", (DL_FUNC) &_MkPrime_eval_log_prior_partitioned_cpp, 8},
    {"_MkPrime_set_class_rate_concentration", (DL_FUNC) &_MkPrime_set_class_rate_concentration, 2},
    {"_MkPrime_eval_full_loglik_cpp", (DL_FUNC) &_MkPrime_eval_full_loglik_cpp, 2},
    {"_MkPrime_eval_full_loglik_at_cpp", (DL_FUNC) &_MkPrime_eval_full_loglik_at_cpp, 5},
    {"_MkPrime_eval_preorder_paths_cpp", (DL_FUNC) &_MkPrime_eval_preorder_paths_cpp, 5},
    {"_MkPrime_gibbs_spr_enumerate_cpp", (DL_FUNC) &_MkPrime_gibbs_spr_enumerate_cpp, 3},
    {"_MkPrime_bin_mixture_log_density", (DL_FUNC) &_MkPrime_bin_mixture_log_density, 3},
    {"_MkPrime_kprime_sweep_candidates", (DL_FUNC) &_MkPrime_kprime_sweep_candidates, 3},
    {"_MkPrime_do_move_cpp", (DL_FUNC) &_MkPrime_do_move_cpp, 8},
    {"_MkPrime_run_mcmc_batch_cpp", (DL_FUNC) &_MkPrime_run_mcmc_batch_cpp, 20},
    {"_MkPrime_debug_mcmc_data", (DL_FUNC) &_MkPrime_debug_mcmc_data, 1},
    {"_MkPrime_validate_swap_partial_cl", (DL_FUNC) &_MkPrime_validate_swap_partial_cl, 3},
    {"_MkPrime_test_persite_uncollapsed", (DL_FUNC) &_MkPrime_test_persite_uncollapsed, 6},
    {"_MkPrime_test_persite_collapsed", (DL_FUNC) &_MkPrime_test_persite_collapsed, 7},
    {"_MkPrime_test_flat_jc_uncollapsed", (DL_FUNC) &_MkPrime_test_flat_jc_uncollapsed, 7},
    {"_MkPrime_test_flat_jc_collapsed", (DL_FUNC) &_MkPrime_test_flat_jc_collapsed, 8},
    {"_MkPrime_test_flat_jc_constprob_pair", (DL_FUNC) &_MkPrime_test_flat_jc_constprob_pair, 8},
    {"_MkPrime_het_const_site_prob", (DL_FUNC) &_MkPrime_het_const_site_prob, 8},
    {"_MkPrime_prepare_mcmc_data", (DL_FUNC) &_MkPrime_prepare_mcmc_data, 31},
    {"_MkPrime_set_branch_bins", (DL_FUNC) &_MkPrime_set_branch_bins, 2},
    {"_MkPrime_set_kprime_trunc_k", (DL_FUNC) &_MkPrime_set_kprime_trunc_k, 2},
    {"_MkPrime_cpp_log_likelihood_xptr", (DL_FUNC) &_MkPrime_cpp_log_likelihood_xptr, 9},
    {"_MkPrime_cpp_log_likelihood_partitioned_xptr", (DL_FUNC) &_MkPrime_cpp_log_likelihood_partitioned_xptr, 10},
    {"_MkPrime_cpp_data_nclasses", (DL_FUNC) &_MkPrime_cpp_data_nclasses, 1},
    {"_MkPrime_spr_proposal", (DL_FUNC) &_MkPrime_spr_proposal, 4},
    {"_MkPrime_beta_simplex_proposal", (DL_FUNC) &_MkPrime_beta_simplex_proposal, 3},
    {"_MkPrime_dirichlet_simplex_proposal", (DL_FUNC) &_MkPrime_dirichlet_simplex_proposal, 3},
    {"_MkPrime_local_dirichlet_proposal", (DL_FUNC) &_MkPrime_local_dirichlet_proposal, 5},
    {"_MkPrime_jc_transition_probs", (DL_FUNC) &_MkPrime_jc_transition_probs, 2},
    {"_MkPrime_mkn_transition_probs", (DL_FUNC) &_MkPrime_mkn_transition_probs, 2},
    {"_MkPrime_mkn_stationary_freqs", (DL_FUNC) &_MkPrime_mkn_stationary_freqs, 1},
    {"_MkPrime_frechet_correlation_ess_cpp", (DL_FUNC) &_MkPrime_frechet_correlation_ess_cpp, 2},
    {"_MkPrime_median_pseudo_ess_cpp", (DL_FUNC) &_MkPrime_median_pseudo_ess_cpp, 3},
    {"_MkPrime_tbr_proposal", (DL_FUNC) &_MkPrime_tbr_proposal, 4},
    {"_MkPrime_swap_subtrees_cpp", (DL_FUNC) &_MkPrime_swap_subtrees_cpp, 6},
    {"_MkPrime_get_valid_swap_partners_cpp", (DL_FUNC) &_MkPrime_get_valid_swap_partners_cpp, 3},
    {"_MkPrime_nni_proposal", (DL_FUNC) &_MkPrime_nni_proposal, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_MkPrime(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
