# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pruning_jc_acrv <- function(parent, child, edge_length, tip_states, kStates, root_freqs, rate_multipliers) {
    .Call(`_MkPrime_pruning_jc_acrv`, parent, child, edge_length, tip_states, kStates, root_freqs, rate_multipliers)
}

pruning_jc_acrv_collapsed <- function(parent, child, edge_length, tip_states, kFull, kObs, rate_multipliers) {
    .Call(`_MkPrime_pruning_jc_acrv_collapsed`, parent, child, edge_length, tip_states, kFull, kObs, rate_multipliers)
}

pruning_mkn_acrv <- function(parent, child, edge_length, tip_states, rate_loss, root_freqs, rate_multipliers) {
    .Call(`_MkPrime_pruning_mkn_acrv`, parent, child, edge_length, tip_states, rate_loss, root_freqs, rate_multipliers)
}

constant_site_prob_jc <- function(parent, child, edge_length, nTip, kStates, root_freqs, rate_multipliers) {
    .Call(`_MkPrime_constant_site_prob_jc`, parent, child, edge_length, nTip, kStates, root_freqs, rate_multipliers)
}

singleton_site_prob_jc <- function(parent, child, edge_length, nTip, kStates, root_freqs, rate_multipliers) {
    .Call(`_MkPrime_singleton_site_prob_jc`, parent, child, edge_length, nTip, kStates, root_freqs, rate_multipliers)
}

constant_site_prob_jc_collapsed <- function(parent, child, edge_length, nTip, kFull, kObs, rate_multipliers) {
    .Call(`_MkPrime_constant_site_prob_jc_collapsed`, parent, child, edge_length, nTip, kFull, kObs, rate_multipliers)
}

singleton_site_prob_jc_collapsed <- function(parent, child, edge_length, nTip, kFull, kObs, rate_multipliers) {
    .Call(`_MkPrime_singleton_site_prob_jc_collapsed`, parent, child, edge_length, nTip, kFull, kObs, rate_multipliers)
}

constant_site_prob_mkn <- function(parent, child, edge_length, nTip, rate_loss, root_freqs, rate_multipliers) {
    .Call(`_MkPrime_constant_site_prob_mkn`, parent, child, edge_length, nTip, rate_loss, root_freqs, rate_multipliers)
}

singleton_site_prob_mkn <- function(parent, child, edge_length, nTip, rate_loss, root_freqs, rate_multipliers) {
    .Call(`_MkPrime_singleton_site_prob_mkn`, parent, child, edge_length, nTip, rate_loss, root_freqs, rate_multipliers)
}

mk_prime_relabel_log <- function(kPrime, kObs) {
    .Call(`_MkPrime_mk_prime_relabel_log`, kPrime, kObs)
}

mk_prime_relabel_log_batch <- function(kPrime_vec, kObs) {
    .Call(`_MkPrime_mk_prime_relabel_log_batch`, kPrime_vec, kObs)
}

mkp_hello <- function() {
    .Call(`_MkPrime_mkp_hello`)
}

pruning_jc <- function(parent, child, edge_length, tip_states, kStates, root_freqs) {
    .Call(`_MkPrime_pruning_jc`, parent, child, edge_length, tip_states, kStates, root_freqs)
}

pruning_jc_collapsed <- function(parent, child, edge_length, tip_states, kFull, kObs) {
    .Call(`_MkPrime_pruning_jc_collapsed`, parent, child, edge_length, tip_states, kFull, kObs)
}

pruning_mkn <- function(parent, child, edge_length, tip_states, rate_loss, root_freqs) {
    .Call(`_MkPrime_pruning_mkn`, parent, child, edge_length, tip_states, rate_loss, root_freqs)
}

bactrian_draws <- function(n) {
    .Call(`_MkPrime_bactrian_draws`, n)
}

bactrian_2d_draws <- function(n, rho) {
    .Call(`_MkPrime_bactrian_2d_draws`, n, rho)
}

fitch_score_r <- function(parent, child, tipStates, nTip, kStates) {
    .Call(`_MkPrime_fitch_score_r`, parent, child, tipStates, nTip, kStates)
}

fitch_score_candidates_r <- function(parent, child, tipStates, nTip, kStates, pruneRow, parentRow, sibRow, u, v, sibNode, candidates) {
    .Call(`_MkPrime_fitch_score_candidates_r`, parent, child, tipStates, nTip, kStates, pruneRow, parentRow, sibRow, u, v, sibNode, candidates)
}

init_mcmc_state <- function(parent, child, relBrLengths, treeLength, rateLoss, rateLogSd, rateNeo, p, kPrime, logLik, logPrior, betaScale = 1.0, kprimeAlpha = 1.0, kprimeBeta = 1.0, classRateLogSd = numeric(0), classW = numeric(0), classRate = numeric(0), nCharPerClass = integer(0), etaNeo = 1.0, useHyperpriorOnSigma = FALSE, hyperTau = 1.0, classZ = numeric(0)) {
    .Call(`_MkPrime_init_mcmc_state`, parent, child, relBrLengths, treeLength, rateLoss, rateLogSd, rateNeo, p, kPrime, logLik, logPrior, betaScale, kprimeAlpha, kprimeBeta, classRateLogSd, classW, classRate, nCharPerClass, etaNeo, useHyperpriorOnSigma, hyperTau, classZ)
}

fill_partition_cache <- function(dataPtr, statePtr) {
    invisible(.Call(`_MkPrime_fill_partition_cache`, dataPtr, statePtr))
}

allocate_cl_workspace <- function(dataPtr, statePtr) {
    invisible(.Call(`_MkPrime_allocate_cl_workspace`, dataPtr, statePtr))
}

get_mcmc_state <- function(statePtr) {
    .Call(`_MkPrime_get_mcmc_state`, statePtr)
}

compute_topo_hash <- function(parent, child, nTip) {
    .Call(`_MkPrime_compute_topo_hash`, parent, child, nTip)
}

node_cl_ready <- function(statePtr) {
    .Call(`_MkPrime_node_cl_ready`, statePtr)
}

get_state_log_lik <- function(statePtr) {
    .Call(`_MkPrime_get_state_log_lik`, statePtr)
}

get_marginal_cache_state <- function(statePtr) {
    .Call(`_MkPrime_get_marginal_cache_state`, statePtr)
}

invalidate_marginal_cache <- function(statePtr) {
    invisible(.Call(`_MkPrime_invalidate_marginal_cache`, statePtr))
}

eval_log_prior_cpp <- function(dataPtr, statePtr) {
    .Call(`_MkPrime_eval_log_prior_cpp`, dataPtr, statePtr)
}

eval_log_prior_partitioned_cpp <- function(dataPtr, statePtr, classRateLogSd, classW, etaNeo, useHyperpriorOnSigma = FALSE, hyperTau = 1.0, classZ = as.numeric( c())) {
    .Call(`_MkPrime_eval_log_prior_partitioned_cpp`, dataPtr, statePtr, classRateLogSd, classW, etaNeo, useHyperpriorOnSigma, hyperTau, classZ)
}

set_class_rate_concentration <- function(dataPtr, concentration) {
    invisible(.Call(`_MkPrime_set_class_rate_concentration`, dataPtr, concentration))
}

eval_full_loglik_cpp <- function(dataPtr, statePtr) {
    .Call(`_MkPrime_eval_full_loglik_cpp`, dataPtr, statePtr)
}

eval_full_loglik_at_cpp <- function(dataPtr, statePtr, parent, child, edgeLen) {
    .Call(`_MkPrime_eval_full_loglik_at_cpp`, dataPtr, statePtr, parent, child, edgeLen)
}

eval_preorder_paths_cpp <- function(dataPtr, statePtr, parent, child, edgeLen) {
    .Call(`_MkPrime_eval_preorder_paths_cpp`, dataPtr, statePtr, parent, child, edgeLen)
}

gibbs_spr_enumerate_cpp <- function(dataPtr, statePtr, pruneRow) {
    .Call(`_MkPrime_gibbs_spr_enumerate_cpp`, dataPtr, statePtr, pruneRow)
}

bin_mixture_log_density <- function(weights, f, nBins) {
    .Call(`_MkPrime_bin_mixture_log_density`, weights, f, nBins)
}

kprime_sweep_candidates <- function(dataPtr, statePtr, beta = 1.0) {
    .Call(`_MkPrime_kprime_sweep_candidates`, dataPtr, statePtr, beta)
}

do_move_cpp <- function(dataPtr, statePtr, moveType, charIdx, scaleTuning, betaSimplexTuning, intWalkWindow, beta) {
    .Call(`_MkPrime_do_move_cpp`, dataPtr, statePtr, moveType, charIdx, scaleTuning, betaSimplexTuning, intWalkWindow, beta)
}

run_mcmc_batch_cpp <- function(dataPtr, stateXPtrs, betas, moveTypeCodes, transIdxCpp, sliceParamCodes, moveWeights, chainScaleTunings, chainBsmpTunings, chainIntWalkWins, moveIntParams, sliceWidths, jointRhos, nBatch, startIter, warmup, thin, hasNeo, nEdge, cacheBonus = 1.0) {
    .Call(`_MkPrime_run_mcmc_batch_cpp`, dataPtr, stateXPtrs, betas, moveTypeCodes, transIdxCpp, sliceParamCodes, moveWeights, chainScaleTunings, chainBsmpTunings, chainIntWalkWins, moveIntParams, sliceWidths, jointRhos, nBatch, startIter, warmup, thin, hasNeo, nEdge, cacheBonus)
}

debug_mcmc_data <- function(dataPtr) {
    .Call(`_MkPrime_debug_mcmc_data`, dataPtr)
}

validate_swap_partial_cl <- function(dataPtr, statePtr, nodeA) {
    .Call(`_MkPrime_validate_swap_partial_cl`, dataPtr, statePtr, nodeA)
}

test_persite_uncollapsed <- function(parent, child, edge_length, tip_states, kStates, rate_multipliers) {
    .Call(`_MkPrime_test_persite_uncollapsed`, parent, child, edge_length, tip_states, kStates, rate_multipliers)
}

test_persite_collapsed <- function(parent, child, edge_length, tip_states, kFull, kObs, rate_multipliers) {
    .Call(`_MkPrime_test_persite_collapsed`, parent, child, edge_length, tip_states, kFull, kObs, rate_multipliers)
}

test_flat_jc_uncollapsed <- function(parent, child, edge_length, tip_states, kStates, acrv, rate_multipliers) {
    .Call(`_MkPrime_test_flat_jc_uncollapsed`, parent, child, edge_length, tip_states, kStates, acrv, rate_multipliers)
}

test_flat_jc_collapsed <- function(parent, child, edge_length, tip_states, kFull, kObs, acrv, rate_multipliers) {
    .Call(`_MkPrime_test_flat_jc_collapsed`, parent, child, edge_length, tip_states, kFull, kObs, acrv, rate_multipliers)
}

test_flat_jc_constprob_pair <- function(parent, child, edge_length, tip_states, kFull, kObs, acrv, rate_multipliers) {
    .Call(`_MkPrime_test_flat_jc_constprob_pair`, parent, child, edge_length, tip_states, kFull, kObs, acrv, rate_multipliers)
}

het_const_site_prob <- function(parent, child, edgeLength, nTip, kStates, baseRateLoss, betaBins, rateMultipliers) {
    .Call(`_MkPrime_het_const_site_prob`, parent, child, edgeLength, nTip, kStates, baseRateLoss, betaBins, rateMultipliers)
}

prepare_mcmc_data <- function(partitions_r, kObs_r, charTypes_r, hasNeo, nCat, codingStr, relabelFlag, treeLengthShape, treeLengthRate, rateLossMeanlog, rateLossSdlog, rateLogSdShape, rateLogSdRate, rateNeoMeanlog, rateNeoSdlog, kprimeHyperA, kprimeHyperB, kPriorLogseries, kprimeLogseriesC, kPriorBetaGeometric = FALSE, qHeterogeneity = FALSE, nBetaCat = 4L, betaScaleShape = 1.0, betaScaleRate = 1.0, kPriorEmpiricalGeometric = FALSE, empLogBody = numeric(), empTailStartK = 0L, empTailDecay = 0.0, empLogTailStartP = -1e308, marginalK = FALSE, unconditionalPrior = FALSE) {
    .Call(`_MkPrime_prepare_mcmc_data`, partitions_r, kObs_r, charTypes_r, hasNeo, nCat, codingStr, relabelFlag, treeLengthShape, treeLengthRate, rateLossMeanlog, rateLossSdlog, rateLogSdShape, rateLogSdRate, rateNeoMeanlog, rateNeoSdlog, kprimeHyperA, kprimeHyperB, kPriorLogseries, kprimeLogseriesC, kPriorBetaGeometric, qHeterogeneity, nBetaCat, betaScaleShape, betaScaleRate, kPriorEmpiricalGeometric, empLogBody, empTailStartK, empTailDecay, empLogTailStartP, marginalK, unconditionalPrior)
}

set_branch_bins <- function(dataPtr, nBins) {
    invisible(.Call(`_MkPrime_set_branch_bins`, dataPtr, nBins))
}

set_kprime_trunc_k <- function(dataPtr, K) {
    invisible(.Call(`_MkPrime_set_kprime_trunc_k`, dataPtr, K))
}

cpp_log_likelihood_xptr <- function(dataPtr, parent, child, edgeLen, kPrime, rateLoss, rateLogSd, rateNeo, betaScale = 1.0) {
    .Call(`_MkPrime_cpp_log_likelihood_xptr`, dataPtr, parent, child, edgeLen, kPrime, rateLoss, rateLogSd, rateNeo, betaScale)
}

cpp_log_likelihood_partitioned_xptr <- function(dataPtr, parent, child, edgeLen, kPrime, rateLoss, rateLogSd, classRate, etaNeo, betaScale = 1.0) {
    .Call(`_MkPrime_cpp_log_likelihood_partitioned_xptr`, dataPtr, parent, child, edgeLen, kPrime, rateLoss, rateLogSd, classRate, etaNeo, betaScale)
}

cpp_data_nclasses <- function(dataPtr) {
    .Call(`_MkPrime_cpp_data_nclasses`, dataPtr)
}

spr_proposal <- function(edge, nTip, treeLength, relBrLengths) {
    .Call(`_MkPrime_spr_proposal`, edge, nTip, treeLength, relBrLengths)
}

beta_simplex_proposal <- function(x, index, tuning) {
    .Call(`_MkPrime_beta_simplex_proposal`, x, index, tuning)
}

dirichlet_simplex_proposal <- function(x, nCats, alpha) {
    .Call(`_MkPrime_dirichlet_simplex_proposal`, x, nCats, alpha)
}

local_dirichlet_proposal <- function(x, parent, child, nCats, alpha) {
    .Call(`_MkPrime_local_dirichlet_proposal`, x, parent, child, nCats, alpha)
}

jc_transition_probs <- function(k, t) {
    .Call(`_MkPrime_jc_transition_probs`, k, t)
}

mkn_transition_probs <- function(rate_loss, t) {
    .Call(`_MkPrime_mkn_transition_probs`, rate_loss, t)
}

mkn_stationary_freqs <- function(rate_loss) {
    .Call(`_MkPrime_mkn_stationary_freqs`, rate_loss)
}

frechet_correlation_ess_cpp <- function(dmat_sq, min_nsamples) {
    .Call(`_MkPrime_frechet_correlation_ess_cpp`, dmat_sq, min_nsamples)
}

median_pseudo_ess_cpp <- function(dmat, min_nsamples, max_rows) {
    .Call(`_MkPrime_median_pseudo_ess_cpp`, dmat, min_nsamples, max_rows)
}

tbr_proposal <- function(edge, nTip, treeLength, relBrLengths) {
    .Call(`_MkPrime_tbr_proposal`, edge, nTip, treeLength, relBrLengths)
}

swap_subtrees_cpp <- function(edge, nTip, treeLength, relBrLengths, nodeA, nodeB) {
    .Call(`_MkPrime_swap_subtrees_cpp`, edge, nTip, treeLength, relBrLengths, nodeA, nodeB)
}

get_valid_swap_partners_cpp <- function(edge, nTip, pruneNode) {
    .Call(`_MkPrime_get_valid_swap_partners_cpp`, edge, nTip, pruneNode)
}

nni_proposal <- function(edge, nTip, treeLength, relBrLengths) {
    .Call(`_MkPrime_nni_proposal`, edge, nTip, treeLength, relBrLengths)
}

