# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mk_prime_relabel_log <- function(kPrime, kObs) {
    .Call(`_MkPrime_mk_prime_relabel_log`, kPrime, kObs)
}

mk_prime_relabel_log_batch <- function(kPrime_vec, kObs) {
    .Call(`_MkPrime_mk_prime_relabel_log_batch`, kPrime_vec, kObs)
}

mkp_hello <- function() {
    .Call(`_MkPrime_mkp_hello`)
}

pruning_jc <- function(parent, child, edge_length, tip_states, kStates, root_freqs) {
    .Call(`_MkPrime_pruning_jc`, parent, child, edge_length, tip_states, kStates, root_freqs)
}

pruning_mkn <- function(parent, child, edge_length, tip_states, rate_loss, root_freqs) {
    .Call(`_MkPrime_pruning_mkn`, parent, child, edge_length, tip_states, rate_loss, root_freqs)
}

jc_transition_probs <- function(k, t) {
    .Call(`_MkPrime_jc_transition_probs`, k, t)
}

mkn_transition_probs <- function(rate_loss, t) {
    .Call(`_MkPrime_mkn_transition_probs`, rate_loss, t)
}

mkn_stationary_freqs <- function(rate_loss) {
    .Call(`_MkPrime_mkn_stationary_freqs`, rate_loss)
}

