on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/rchk.yml'
      - 'src/**'
      - 'inst/include/**'
      - 'memcheck/**'
      - 'tests/testthat/**.R'
      - 'vignettes/**.qmd'
  pull_request:
    paths:
      - '.github/workflows/rchk.yml'
      - 'src/**'
      - 'inst/include/**'
      - 'memcheck/**'
      - 'tests/testthat/**.R'
      - 'vignettes/**.qmd'

name: rchk

jobs:
  rchk:
    runs-on: ubuntu-latest
    container:
      image: rhub/ubuntu-rchk
      options: --user=root
    steps:
    - uses: actions/checkout@v6

    - uses: randy3k/gh-actions/r-rchk@main
      with:
        cache-version: rchk-1
